#!/bin/python3

import sys

def birthdayCakeCandles(n, ar):
    max=0
    count=0
    for i in range(0,n):
        if(max<ar[i]):
            max=ar[i]
    for i in range (0,n):
        if(max==ar[i]):
            count=count+1
    return (count)
        
           
    

n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
result = birthdayCakeCandles(n, ar)
print(result)
