#!/bin/python3

import sys

ab=0
b=0
n = int(input().strip())
a = []

for a_i in range(n):
    a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
    a.append(a_t)
    ab=ab+a_t[a_i]
    b=b+a_t[(n-1)-a_i]
res=abs(ab-b)
print(res)
